version: '3'

services:
  mysql:
    image: mysql:5.7.29
    platform: linux/amd64
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dumbbelloper
      MYSQL_USER: dumbbelloper
      MYSQL_PASSWORD: dumbbelloper
      MYSQL_ROOT_PASSWORD: dumbbelloper
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
